# Generated by Django 2.0.9 on 2019-01-22 08:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
